version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - TELEGRAM_TOKEN=your_telegram_token_here
      # Добавь другие переменные, если нужно
